# Generated by Django 3.1.7 on 2021-08-15 20:42

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_live_stem'),
    ]

    operations = [
        migrations.CreateModel(
            name='cameronack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acks', models.TextField(default='No acknowledgements uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='cameronbio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='No bio uploaded')),
                ('asideOne', models.TextField(default='No first aside uploaded')),
                ('asideTwo', models.TextField(default='No second aside uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='cameroncontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cameronlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.TextField(default='No links uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='cameronnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(default='No file uploaded')),
                ('img1', models.ImageField(default='No file uploaded', upload_to='')),
                ('img2', models.ImageField(default='No file uploaded', upload_to='')),
                ('img3', models.ImageField(default='No file uploaded', upload_to='')),
                ('img4', models.ImageField(default='No file uploaded', upload_to='')),
                ('img5', models.ImageField(default='No file uploaded', upload_to='')),
                ('img6', models.ImageField(default='No file uploaded', upload_to='')),
                ('img7', models.ImageField(default='No file uploaded', upload_to='')),
                ('img8', models.ImageField(default='No file uploaded', upload_to='')),
                ('img9', models.ImageField(default='No file uploaded', upload_to='')),
                ('img10', models.ImageField(default='No file uploaded', upload_to='')),
                ('img11', models.ImageField(default='No file uploaded', upload_to='')),
                ('img12', models.ImageField(default='No file uploaded', upload_to='')),
                ('img13', models.ImageField(default='No file uploaded', upload_to='')),
                ('img14', models.ImageField(default='No file uploaded', upload_to='')),
                ('img15', models.ImageField(default='No file uploaded', upload_to='')),
                ('img16', models.ImageField(default='No file uploaded', upload_to='')),
                ('img17', models.ImageField(default='No file uploaded', upload_to='')),
                ('img18', models.ImageField(default='No file uploaded', upload_to='')),
                ('img19', models.ImageField(default='No file uploaded', upload_to='')),
                ('img20', models.ImageField(default='No file uploaded', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='cameronworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works', models.TextField(default='No works uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dkhabout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='No info uploaded')),
                ('img1', models.ImageField(default='No file uploaded', upload_to='')),
                ('img2', models.ImageField(default='No file uploaded', upload_to='')),
                ('img3', models.ImageField(default='No file uploaded', upload_to='')),
                ('img4', models.ImageField(default='No file uploaded', upload_to='')),
                ('img5', models.ImageField(default='No file uploaded', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='dkhcontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dkhhome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage', models.TextField(default='No homepage uploaded')),
                ('img1', models.ImageField(default='No file uploaded', upload_to='')),
                ('img2', models.ImageField(default='No file uploaded', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='dkhlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.TextField(default='No links uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='dkhlisten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen', models.TextField(default='No audio uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='dkhnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(default='No file uploaded')),
                ('img1', models.ImageField(default='No file uploaded', upload_to='')),
                ('img2', models.ImageField(default='No file uploaded', upload_to='')),
                ('img3', models.ImageField(default='No file uploaded', upload_to='')),
                ('img4', models.ImageField(default='No file uploaded', upload_to='')),
                ('img5', models.ImageField(default='No file uploaded', upload_to='')),
                ('img6', models.ImageField(default='No file uploaded', upload_to='')),
                ('img7', models.ImageField(default='No file uploaded', upload_to='')),
                ('img8', models.ImageField(default='No file uploaded', upload_to='')),
                ('img9', models.ImageField(default='No file uploaded', upload_to='')),
                ('img10', models.ImageField(default='No file uploaded', upload_to='')),
                ('img11', models.ImageField(default='No file uploaded', upload_to='')),
                ('img12', models.ImageField(default='No file uploaded', upload_to='')),
                ('img13', models.ImageField(default='No file uploaded', upload_to='')),
                ('img14', models.ImageField(default='No file uploaded', upload_to='')),
                ('img15', models.ImageField(default='No file uploaded', upload_to='')),
                ('img16', models.ImageField(default='No file uploaded', upload_to='')),
                ('img17', models.ImageField(default='No file uploaded', upload_to='')),
                ('img18', models.ImageField(default='No file uploaded', upload_to='')),
                ('img19', models.ImageField(default='No file uploaded', upload_to='')),
                ('img20', models.ImageField(default='No file uploaded', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='emaillist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(default='South Africa', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='tourinput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.TextField(default='No tour uploaded')),
            ],
        ),
    ]
