# Generated by Django 3.1.7 on 2022-02-07 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_cameronack_cameronbio_cameroncontact_cameronlinks_cameronnews_cameronworks_contact_dkhabout_dkhconta'),
    ]

    operations = [
        migrations.CreateModel(
            name='livelarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
