# Generated by Django 3.1.7 on 2022-06-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_livelarge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cameronack',
        ),
        migrations.DeleteModel(
            name='cameronbio',
        ),
        migrations.DeleteModel(
            name='cameroncontact',
        ),
        migrations.DeleteModel(
            name='cameronlinks',
        ),
        migrations.DeleteModel(
            name='cameronnews',
        ),
        migrations.DeleteModel(
            name='cameronworks',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='dkhabout',
        ),
        migrations.DeleteModel(
            name='dkhcontact',
        ),
        migrations.DeleteModel(
            name='dkhhome',
        ),
        migrations.DeleteModel(
            name='dkhlinks',
        ),
        migrations.DeleteModel(
            name='dkhlisten',
        ),
        migrations.DeleteModel(
            name='dkhnews',
        ),
        migrations.DeleteModel(
            name='emaillist',
        ),
        migrations.RemoveField(
            model_name='live',
            name='user',
        ),
        migrations.DeleteModel(
            name='livelarge',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stem',
            name='user',
        ),
        migrations.DeleteModel(
            name='tourinput',
        ),
        migrations.DeleteModel(
            name='live',
        ),
        migrations.DeleteModel(
            name='sound',
        ),
        migrations.DeleteModel(
            name='stem',
        ),
    ]
